fix of condition for onScrollStart
schrodinger/fixed-data-table-2 pull request #559
Opened 2020-09-24 18:57 UTC by marfuzzi

**Fixed condition for scroll callback - onScrollStart**

## Motivation and Context
In this commit https://github.com/schrodinger/fixed-data-table-2/commit/a59831dbb94e8aa64db540aaa7946935d651e1c4#diff-293ddd101833c33e0069803f5068f2f7R1132 condition to call onScrollStart is incorrect, because forgot  to change (!this.props.scrolling -> !prevProps.scrolling)

**onScrollStart** is called if scrolling wasn't on previously and is scrolling now (!prevProps.scrolling && this.props.scrolling)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.

2020-09-25 12:15 UTC, pradeepnschrodinger requested changes

2020-09-25 12:15 UTC, pradeepnschrodinger commented on src/FixedDataTable.js
> +    if (!prevProps.scrolling && this.props.scrolling && onScrollStart) {
Let's destructure `scrolling` from `prevProps` and `this.props` above.
Then `scrolling` will refer to the new value, and `oldScrolling` will refer to the previous value.

2020-09-25 12:23 UTC, pradeepnschrodinger commented
@marfuzzi , lets put this fix for the branch [v1.1.x](https://github.com/schrodinger/fixed-data-table-2/commits/v1.1.x) since that's where the regression was introduced.

2020-09-29 20:37 UTC, marfuzzi commented
> @marfuzzi , lets put this fix for the branch [v1.1.x](https://github.com/schrodinger/fixed-data-table-2/commits/v1.1.x) since that's where the regression was introduced.

done! https://github.com/schrodinger/fixed-data-table-2/pull/561

2020-10-27 22:20 UTC, pradeepnschrodinger commented
closed through #561

2020-10-27 22:20 UTC, closed without merging