Add null checks to prevent client exception when reading 'releaseMouseMoves;
schrodinger/fixed-data-table-2 pull request #615
Opened 2021-11-22 15:42 UTC by Tanner-MS

Through telemetry of our product usage of the fixed-data-table-2 we are seeing the following client exception happen at times:
TypeError: Cannot read property 'releaseMouseMoves' of null

## Description
Add null checks similar to one that was already there to all calls to releaseMouseMoves. I am not sure of the reproduction steps needed but felt like adding a null check would not hurt anything.

## Motivation and Context
This is to prevent exceptions seen by some of our end users.

## How Has This Been Tested?
N/A

## Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.

2021-11-23 14:14 UTC, pradeepnschrodinger requested changes
Thanks for adding the safety checks. 

Could you change the base branch for the PR to `v1.2.x` ?

2021-11-23 14:16 UTC, pradeepnschrodinger commented on src/plugins/Scrollbar.js
> +      this._mouseMoveTracker.releaseMouseMoves();
and remove the delete call below (just for consistency with other parts of the codebase)

2021-11-23 15:30 UTC, Tanner-MS commented
> Thanks for adding the safety checks.
> 
> Could you change the base branch for the PR to `v1.2.x` ?

I wasnt sure how to do that so I created a new PR and will cancel this one.

2021-11-23 15:31 UTC, closed without merging

2021-11-24 08:39 UTC, pradeepnschrodinger commented
> > Could you change the base branch for the PR to `v1.2.x` ?
> 
> I wasnt sure how to do that so I created a new PR and will cancel this one. #616

One way is to "edit" the PR and change the base branch displayed under the PR title. Creating a new PR is fine too, thanks.